### ISSUE TITLE
Improve documentation and samples for swagger plugins

### ISSUE THREAD

**Issue by twatzl** [cloudflightio/cloudflight-platform-spring#89]
I am just trying to use the swagger autoconfigure plugin in a project. 

Unfortunately the kotlin-springboot-angular sample is already quite old, uses gradle groovy (not kts) and does not include codegen.

It would be helpful if there was a sample that generates the API docs from an api, but then also uses that code to generate a Java/Kotlin and npm clients. Ideally one that runs without spring, so that pure java/kotlin clients (like Android) can also use it.

Edit: It would also be great if the sample showed a minimum example using the least amount of libraries possible and not pull in the whole Spring framework for generating a Java Api Client.

**Comment by rspiegl** [comment]
I assume you mean this repo https://github.com/cloudflightio/autoconfigure-gradle-plugin for the swagger autoconfigure plugin. The sample you mention is an internal repo, so please forward your feedback regarding the sample internally to the appropriate places.
With this information I will close this issue as nothing of the reported issues concerns this repo.
Please bring your issues to the above mentioned repos.
